### ISSUE TITLE
Icon size is too small

### ISSUE THREAD

**Issue by karnadii** [rbcprolabs/icon_font_generator#1]
Hello, i just tried this, but the result icon is so small

![https://i.imgur.com/Hi4qEel.png](https://i.imgur.com/Hi4qEel.png)

look at the top left, bottom right and top right of the screenshott.

in the end I just generate my font with iconmoon and then edit icons.dart generated by this package.

**Comment by karnadii** [comment]
using http://fluttericon.com is also the same, the solution for me is generate the font using https://icomoon.io and then manually edit the file icon.dart generated by this plugin.

**Comment by SergeShkurko** [comment]
@karnadii you can independently correct the svg size in the program [inkscape](https://inkscape.org/)

**Comment by karnadii** [comment]
already did that and still the same. or maybe when I generate the new one, it still generate the old one. last time I try this, I have to do flutter clean. to generate the new one. If I dont do flutter clean, the icons generated are the old one.

**Comment by SergeShkurko** [comment]
To load new icons you need:
1. Stop projet build
2. Run `flutter clean`
3. Generate icons
4. Run project build

**Comment by SergeShkurko** [comment]
Added flag `normalize` in v1.0.0

**Comment by pacodiem** [comment]
I know this is closed, but I had the same issue when I uploaded my custom icons in fluttericon.com
By opening the svg file in a text editor I noticed that it has this property `transform="scale(0.26458333)"`
I set the scale to `1` and the icon now has the correct size.
Hope this helps.

**Comment by G11Max** [comment]
> I know this is closed, but I had the same issue when I uploaded my custom icons in fluttericon.com By opening the svg file in a text editor I noticed that it has this property `transform="scale(0.26458333)"` I set the scale to `1` and the icon now has the correct size. Hope this helps.

I solved it by setting the width and height of the svg file.


```svg
<!-- width: 24 -> 240
height:  24 -> 240  -->

<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="240" height="240">
  <path fill="none" d="M0 0h24v24H0z" />
  <path d="M18.031 16.617l4.283 4.282-1.415 1.415-4.282-4.283A8.96 8.96 0 0 1 11 20c-4.968 0-9-4.032-9-9s4.032-9 9-9 9 4.032 9 9a8.96 8.96 0 0 1-1.969 5.617z" fill="#000" />
</svg>

```

**Comment by iqfareez** [comment]
Very helpful thread. For me using Inkscape, I had to set the scale to `1`. And set the document size same as object

![image](https://user-images.githubusercontent.com/60868965/221348041-ffde0836-67cc-4ddc-85e3-780236a0adf5.png)
