### ISSUE TITLE
Error with IconData

### ISSUE THREAD

**Issue by corusm** [rbcprolabs/icon_font_generator#12]
lib/widgets/icons.dart(1099,16): error GBE42D792: 'IconData' isn't a type. [[C:\Users\len5due\Music\baustellentool\build\windows\flutter\flutter_assemble.vcxproj]

Problem in Windows with the IconData Datatype

**Comment by SergeShkurko** [comment]
`IconData` importing from 'package:flutter/widgets.dart'
Maybe problem in you build configuration
