### ISSUE TITLE
Error when running the generator: `bin/generate.dart` does not exists

### ISSUE THREAD

**Issue by jonashoelzel** [rbcprolabs/icon_font_generator#36]
When running `dart run icon_font_generator:generate` I get this error:

```
Could not find `bin/generate.dart` in package `icon_font_generator`.
```

The file `bin/generate.dart` exists in `~/.pub-cache/hosted/pub.dev/icon_font_generator-4.0.0/`

How can I fix this? (I'm on a Mac)

**Comment by stevenosse** [comment]
Hey
I had the same issue. It worked using "generator" instead of "generate":

```shell
$ dart run icon_font_generator:generate
```

**Comment by jonashoelzel** [comment]
Thanks for the response, but I think your command is the exact same as mine. It still does not work for me.

**Comment by stevenosse** [comment]
Hi
Sorry, I meant

```shell
$ dart run icon_font_generator:generator
```

**Comment by jonashoelzel** [comment]
This is working. Thanks!

**Comment by donik1998** [comment]
Guys need a fix in docs. 
```
$ flutter pub add --dev icon_font_generator

# And it's ready to go:
$ flutter pub run icon_font_generator:generate <input-svg-dir> <output-font-file> [options]
```

Second command doesn't work. Need to fix a typo in `generate`. It should be `generator` instead. 
So, it is gonna be
```
flutter pub run icon_font_generator:generator <input-svg-dir> <output-font-file> [options]
```

**Comment by hanskokx** [comment]
Even with the `generator`, I'm still getting this issue on v3.2.0.

**Comment by andreypUP** [comment]
Can you please change the command in `README.MD` to this `dart run icon_font_generator:generator`

**Comment by KiddoV** [comment]
I am still having issue with verison `v3.2.0`
Run `> dart run icon_font_generator:generator`
Got error:
```error
Could not find `bin\generator.dart` in package `icon_font_generator`.
```
