### ISSUE TITLE
dart class generation not working

### ISSUE THREAD

**Issue by rsurkin** [rbcprolabs/icon_font_generator#7]
dart class generation not working

stack 

Unhandled exception:
Invalid argument(s): Register has invalid characters clock-wait
#0      new Register (package:register/register.dart:15:7)
#1      generateFlutterClass.<anonymous closure> (package:icon_font_generator/generate_flutter_class.dart:25:40)
#2      MappedIterator.moveNext (dart:_internal/iterable.dart:395:18)
#3      Iterable.join (dart:core/iterable.dart:372:23)
#4      generateFlutterClass (package:icon_font_generator/generate_flutter_class.dart:46:57)
<asynchronous suspension>
#5      GenerateCommand.run (file:///Users/karaken/.pub-cache/hosted/pub.dartlang.org/icon_font_generator-1.0.0/bin/icon_font_generator.dart:200:39)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#7      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#8      new Future.sync (dart:async/future.dart:224:31)
#9      CommandRunner.run (package:args/command_runner.dart:112:14)
#10     main (file:///Users/karaken/.pub-cache/hosted/pub.dartlang.org/icon_font_generator-1.0.0/bin/icon_font_generator.dart:13:18)
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by SergeShkurko** [comment]
@rsurkin all icon file names in [snake-case](https://wikipedia.org/wiki/Snake_case)?

**Comment by rsurkin** [comment]
@SergeShkurko no, some of them devided by -,   i will rename and recheck

**Comment by rsurkin** [comment]
promlem in file names, ssory for interupt
